name: continous integration

on:
  push:
   branches:
    -main
  pull_request:
   branches:
    -main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules (resuse cached modules)
        uses: actions/cache@v2
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules (resuse cached modules)
        uses: actions/cache@v2
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'

      - name: Build JavaScript files
        run: npm build

  
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   env: 
  #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #     DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  #   steps: 
  #     - name: Login to Docker
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ env.DOCKER_USERNAME }}
  #         password: ${{ env.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t ${{ env.DOCKER_USERNAME }}/express-boilerplate .
  #         docker push ${{ env.DOCKER_USERNAME }}/express-boilerplate

  #     - name: Deploy to production
  #       run: |
  #         docker run -d -p 3000:3000 ${{ env.DOCKER_USERNAME }}/express-boilerplate
        


      


